package com.annotation.model;

import java.io.Serializable;

public class DoTaskDetail implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotaskdetail.dtdid
     *
     * @mbg.generated
     */
    private Integer dtdid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotaskdetail.dotaskid
     *
     * @mbg.generated
     */
    private Integer dotaskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotaskdetail.labelid
     *
     * @mbg.generated
     */
    private Integer labelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotaskdetail.contentbegin
     *
     * @mbg.generated
     */
    private Integer contentbegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotaskdetail.contentend
     *
     * @mbg.generated
     */
    private Integer contentend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dotaskdetail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public Integer getDtdid() {
        return dtdid;
    }

    public void setDtdid(Integer dtdid) {
        this.dtdid = dtdid;
    }

    public Integer getDoTaskid() {
        return dotaskid;
    }

    public void setDoTaskid(Integer dotaskid) {
        this.dotaskid = dotaskid;
    }

    public Integer getLabelid() {
        return labelid;
    }

    public void setLabelid(Integer labelid) {
        this.labelid = labelid;
    }

    public Integer getContentbegin() {
        return contentbegin;
    }

    public void setContentbegin(Integer contentbegin) {
        this.contentbegin = contentbegin;
    }

    public Integer getContentend() {
        return contentend;
    }

    public void setContentend(Integer contentend) {
        this.contentend = contentend;
    }
}
