package com.annotation.model;

import java.io.Serializable;

public class DoTask implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotask.dtid
     *
     * @mbg.generated
     */
    private Integer dtid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotask.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotask.taskid
     *
     * @mbg.generated
     */
    private Integer taskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotask.contentid
     *
     * @mbg.generated
     */
    private Integer contentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dotask
     *
     * @mbg.generated
     */

    private String dotime;

    private String comptime;

    private String dtstatus;
    private static final long serialVersionUID = 1L;

    public Integer getDtid() {
        return dtid;
    }

    public void setDtid(Integer dtid) {
        this.dtid = dtid;
    }

    public Integer getUserid() {
        return userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public Integer getTaskid() {
        return taskid;
    }

    public void setTaskid(Integer taskid) {
        this.taskid = taskid;
    }

    public Integer getContentid() {
        return contentid;
    }

    public void setContentid(Integer contentid) {
        this.contentid = contentid;
    }

    public String getDotime() {
        return dotime;
    }

    public void setDotime(String dotime) {
        this.dotime = dotime == null ? null : dotime.trim();
    }

    public String getComptime() {
        return comptime;
    }

    public void setComptime(String comptime) {
        this.comptime = comptime == null ? null : comptime.trim();
    }

    public String getDtstatus() {
        return dtstatus;
    }

    public void setDtstatus(String dtstatus) {
        this.dtstatus = dtstatus == null ? null : dtstatus.trim();
    }

}
