package com.annotation.model;

import java.io.Serializable;

public class TaskLabel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_label.taskid
     *
     * @mbg.generated
     */
    private Integer taskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_label.labelid
     *
     * @mbg.generated
     */
    private Integer labelid;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_label
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_label.taskid
     *
     * @return the value of task_label.taskid
     *
     * @mbg.generated
     */
    public Integer getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_label.taskid
     *
     * @param taskid the value for task_label.taskid
     *
     * @mbg.generated
     */
    public void setTaskid(Integer taskid) {
        this.taskid = taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_label.labelid
     *
     * @return the value of task_label.labelid
     *
     * @mbg.generated
     */
    public Integer getLabelid() {
        return labelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_label.labelid
     *
     * @param labelid the value for task_label.labelid
     *
     * @mbg.generated
     */
    public void setLabelid(Integer labelid) {
        this.labelid = labelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label
     *
     * @mbg.generated
     */


    private String color;
    public String getColor(){
        return color;
    }
    public void setColor(String color){
        this.color=color;
    }
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", taskid=").append(taskid);
        sb.append(", labelid=").append(labelid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
